public class leadconvertwrapper {
    public boolean ischangemade;
    public acc ac1;
    public con con1;
    public opp opp1;
    public boolean docreateopp;
    public string owner;
    public string constatus;
    public boolean isexistimgacc;
    public boolean isexistingcon;
    public boolean isexistingopp;
    public string existacc;
    public string existcon;
    public string existopp;
    
    public class acc
    {
        public String compname;
    }
    
    public class con
    {
        public String salu;
        public String fname;
        public String lname;
    }
    
    public class opp
    {
        public string name;
    }
}